[server]
headless = true
port = 8501
enableCORS = false

[runner]
# Add a custom directory for Streamlit
dataFrameSerialization = "legacy"

[global]
# To set a custom config directory
configDir = "/path/to/your/working/directory/.streamlit"
